stages:
  data_loading:
    cmd: python src/data_loading.py
    deps:
      - src/data_loading.py
    params:
      - data.dataset_url
      - data.raw_data_path
    outs:
      - data/raw/online_retail.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/online_retail.csv
    params:
      - preprocessing
      - data.processed_data_path
    outs:
      - data/processed/processed_data.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/processed_data.csv
    params:
      - feature_engineering
      - data.test_size
      - data.random_state
      - data.train_data_path
      - data.test_data_path
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
      - models/scaler.pkl

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed/train.csv
    params:
      - model
      - feature_engineering.target_column
      - mlflow
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - data/processed/train.csv
      - data/processed/test.csv
      - models/model.pkl
    params:
      - evaluation
      - feature_engineering.target_column
    metrics:
      - models/metrics.json:
          cache: false
    plots:
      - models/confusion_matrix.png:
          cache: false
      - models/roc_curve.png:
          cache: false
